const PERMISSIONS = {
  TENANT_READ: 'TENANT_READ',
  TENANT_UPDATE: 'TENANT_UPDATE',
  ASSET_UPLOAD: 'ASSET_UPLOAD',
  ASSET_VERSION_ROLLBACK: 'ASSET_VERSION_ROLLBACK',
  VERIFICATION_REQUEST: 'VERIFICATION_REQUEST',
  VERIFICATION_APPROVE: 'VERIFICATION_APPROVE',
  LOG_VIEW: 'LOG_VIEW',
  LOG_EXPORT: 'LOG_EXPORT',
  USER_INVITE: 'USER_INVITE',
  USER_DISABLE: 'USER_DISABLE',
  USER_ROLE_UPDATE: 'USER_ROLE_UPDATE',
};

module.exports = { PERMISSIONS };
